### ISSUE TITLE
use socket.io connect event to auth instead of my crappy home-grown auth

### ISSUE THREAD

**Issue by beejeebus** [beejeebus/drupal-nodejs#11]
when i wrote this, i put in a crappy home-grown client socket auth path.

we should auth the socket during the connect event (pretty sure we can get at http headers), and ditch my crappy home-grown mechanism.

**Comment by beejeebus** [comment]
aaaaaand, nope. socket.io clients doesn't allow us to set headers. booooooo :-1: 

so, we either leave this as is, or put the token in the query string, or switch to something that doesn't enforce this rather silly abstraction on us (we're always gonna use http).

i think i'd favour leaving it as is until we get other more important things done.

**Comment by glekli** [comment]
As suggested, the authentication was left untouched. Let's reopen when the need to change arises.
