### ISSUE TITLE
healthcheck not returning server version

### ISSUE THREAD

**Issue by Mattkins** [beejeebus/drupal-nodejs#16]
This is causing send_message to fail, since Nodejs::nodeServerVersion isn't being set in the module.

Not sure if it's the appropriate fix, but I added the server variable to all requests so the route can access the version.

**Comment by fortis** [comment]
same problem
`$data = self::httpRequest('nodejs/health/check');`
returns false

**Comment by glekli** [comment]
Thanks for reporting. This has been fixed.
