### ISSUE TITLE
Use POST requests for actions

### ISSUE THREAD

**Issue by beejeebus** [beejeebus/drupal-nodejs#2]
In the nodejs app, some operations are performed using GET requests (e.g. kickUser). According to standards, GET requests are not supposed to change any state on the server. Shall we change these to POST requests?

migrated from https://www.drupal.org/node/2634928

**Comment by glekli** [comment]
I have made this update. Please see it here:

https://github.com/glekli/drupal-nodejs/commit/cfd680c9183cf0efbd51d220b3da51b642490f4d

There is related commit in the Drupal module:

http://cgit.drupalcode.org/nodejs/commit/?id=0557781

**Comment by beejeebus** [comment]
this issue can be closed out, as the code is in with the merging of #4 :-)
