### ISSUE TITLE
Missing '/' in extensions path

### ISSUE THREAD

**Issue by hmoen** [beejeebus/drupal-nodejs#20]
I had to add a '/' behind 'extensions' on line 102 of config-manager.js:
`this.extensions.push(require(__dirname + '/../extensions/' + this.settings.extensions[i]));`
in order for me not to have to add a '/' before each extension name in nodejs.config.js:
`extensions: [],`

If it is designed to work as is, please let me know. Thanks for a great module!

**Comment by glekli** [comment]
Thanks for reporting. This has been fixed.
