### ISSUE TITLE
addClientToChannel: Invalid sessionId

### ISSUE THREAD

**Issue by rhclayto** [beejeebus/drupal-nodejs#23]
I just stumbled upon this:

When calling `clientManager.addClientToChannel(sessionId, message.channel);` from a server extension, I get the an error like this: `addClientToChannel: Invalid sessionId: /#9Ox_G2AhR_iMcETXAAAO`. It appears the regex in `ClientManager.prototype.addClientToChannel` doesn't account for the socket ID generated by socket.io. The current regex is:

```javascript
if (!/^[0-9A-Za-z_-]+$/i.test(sessionId) || !this.sockets.hasOwnProperty(sessionId)) {
  this.logger.log("addClientToChannel: Invalid sessionId: " + sessionId);
}
```

It works if I change it to:

```javascript
if (!/^[0-9A-Za-z_#\/-]+$/i.test(sessionId) || !this.sockets.hasOwnProperty(sessionId)) {
  this.logger.log("addClientToChannel: Invalid sessionId: " + sessionId);
}
```

**Comment by glekli** [comment]
Thanks for reporting. I actually removed the regex check because the other condition validates that the session id already exists in `.sockets`, and if it already exists elsewhere, it must be valid.
