### ISSUE TITLE
Channel isClientWritable is undefined

### ISSUE THREAD

**Issue by heshanlk** [beejeebus/drupal-nodejs#24]
Looks like channels have no property called, isClientWritable. I'm not sure where that is coming from, should it read from the configs?

```
/**
 * Check if the given channel is client-writable.
 */
ClientManager.prototype.channelIsClientWritable = function (channel) {
  if (this.channels.hasOwnProperty(channel)) {
    return this.channels[channel].isClientWritable;
  }
  return false;
};
```

**Comment by glekli** [comment]
This may have been an experimental feature that was never fully developed. It does not seem like it is possible to set that property at this moment.

**Comment by Craigmoore** [comment]
I too have encountered this today. This will never resolve, which means that no channel is ever writeable.

Presumably in future, the writeable flag is something that will come from the Drupal configuration that declares the channels, but this is not part of the d7 module at least.

**Comment by beejeebus** [comment]
sorry for the very delayed reply here.

some context is in order. the node.js server wasn't originally intended to process messages coming from clients. the original use case was:

client -> backend (original use case was Drupal) -> node.js process -> relevant clients

the node.js bits were intended to only handle the persistent connection part of 'real time', and not any of the smarts, like, authentication, authorization, which channels are valid, etc.

at some point (i don't remember when exactly), we decided to allow this faster, and much, much scarier flow:
 
client -> node.js -> client

at this point, i'd be in favor of simply removing that flow.

i hope that helps explain why that code is there, and why it seems like it's half baked.

thoughts?

**Comment by beejeebus** [comment]
@glekli - any objection to me removing this feature?

**Comment by glekli** [comment]
Agreed, it is safer to avoid this feature if we can.
