### ISSUE TITLE
XMPP sync?

### ISSUE THREAD

**Issue by poVoq** [beejeebus/drupal-nodejs#29]
Is there a way to sync this with an XMPP (Prosody) server running on the same machine so that the Drupal chat can use XMPP functionality?

**Comment by beejeebus** [comment]
you could try writing an extension. not sure it's wise to use this module and an XMPP server though, it's probably better to work on integrating the XMPP server directly.

**Comment by beejeebus** [comment]
closing the issue, as it's not something that is possible nor something i want to add.
