### ISSUE TITLE
Remove path configuration in app.js

### ISSUE THREAD

**Issue by beejeebus** [beejeebus/drupal-nodejs#3]
In nodejs.config.js, there is a ton of configuration options that allow you to specify the paths at which the node.js server responds to certain requests (e.g. logoutUserUrl). This seems to be pointless because these paths are hard coded in the Drupal module, so changing any of them would break functionality. In addition, they make the express route definitions look somewhat obfuscated.

Do you think there will be any situation where these would need to be changed? Shall we remove these paths from the configration and consider these paths predetermined and fixed?

Taken from: https://www.drupal.org/node/2634894

**Comment by glekli** [comment]
This was completed in the first round of refactoring.
