### ISSUE TITLE
Not able to fetch User ID 

### ISSUE THREAD

**Issue by bala-drg** [beejeebus/drupal-nodejs#30]
I'm using this library in Drupal and also using Redis cache for session. So when i login in drupal two session values are getting creating on Redis. One with id 0 and other one with actual user id. 
i have created custom nodejs_auth_check_callback to get user id from Redis using session ID to create socket.io channel but channel is created for id 0.

Please help

**Comment by beejeebus** [comment]
i think you need to move this to the Drupal issue queue.
