### ISSUE TITLE
non-drupal clients and REST API

### ISSUE THREAD

**Issue by laurencefass** [beejeebus/drupal-nodejs#32]
was the nodejs app designed to be drupal-centric? 

can/does this app offer a REST API for non-drupal clients?

are there any issues to consider connecting non-drupal (javascript) clients?

is it possible now? is there a REST API? if not, does it sound like a worthwhile feature and could one be easily included?

thanks

**Comment by beejeebus** [comment]
the nodejs was not designed to be a generic app. it was developed to work with Drupal.

however, there's nothing in the design that prevents it being used by other apps that speak the right http to it.

adding a better HTTP API would be great.
