### ISSUE TITLE
add tests, all the tests, any tests will do

### ISSUE THREAD

**Issue by beejeebus** [beejeebus/drupal-nodejs#6]
yeah, this is a bit overdue :-)

@tizzo @glekli - any preferences for what tooling to use to do this?

**Comment by tizzo** [comment]
I usually use mocha and should. They're tried and true and I think sort of the defecto standard in node, though jasmine and a handful of others are around as well.

**Comment by glekli** [comment]
Mocha sounds good. I have no other preference.

**Comment by beejeebus** [comment]
okie dokie, thanks guys, mocha works for me. going to close this and open a smaller scoped issue to add Mocha.
