### ISSUE TITLE
Use body-parser to parse json in requests

### ISSUE THREAD

**Issue by glekli** [beejeebus/drupal-nodejs#7]
Some of the router callbacks add event listers for 'data' and 'end' events on the request object in order to gather the request body, and then convert it to json. This means repetitive code in a few places. I recommend we delegate the json parsing work to body-parser module.

I have made this update in my fork. For some reason, I'm unable to create a PR - perhaps because of the other pending PR. You can see it here:

https://github.com/glekli/drupal-nodejs/commit/93ea1986375ddbde5313f2b9f8fc0e7fa25f3611

**Comment by glekli** [comment]
There is a corresponding commit in the Drupal module. The content-type header needs to be set on requests.

This also includes a minor change where I changed the 'status' code from 'ok' to 'success'. Most callbacks return 'success', and I was trying to standardize the response.

http://cgit.drupalcode.org/nodejs/commit/?id=077c596

**Comment by beejeebus** [comment]
:+1: - i merged #4, so i think we can close this.
