### ISSUE TITLE
write Mocha tests for some http endpoints

### ISSUE THREAD

**Issue by beejeebus** [beejeebus/drupal-nodejs#9]
i've added Mocha as a dependency in package.sjon, so we can start on the tests.

i guess we just pick a couple of endpoints, not sure which, but doesn't matter too much where we start.

**Comment by glekli** [comment]
I have added the first round of tests. These are very basic - just to get the ball rolling.
This has zero impact on everything else, so I went ahead and committed it.

**Comment by beejeebus** [comment]
thanks!

**Comment by beejeebus** [comment]
so i guess the next bit is to wire this all up to Travis.

**Comment by glekli** [comment]
I added some more tests.

**Comment by beejeebus** [comment]
closing this as fixed, we can open more specific issues as we see fit.
